steps:
  - id: docker-build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}:latest
      - .

  - id: docker-push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}
    waitFor: [docker-build]

  - id: cloud-run-deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_APP_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}:${SHORT_SHA}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --quiet
    waitFor: [docker-push]

substitutions:
  _REGION: europe-central2
  _APP_NAME: docscanner

options:
  logging: CLOUD_LOGGING_ONLY
